### ISSUE TITLE
Is it planned to release v1.12.0 also on npmjs?

### ISSUE THREAD

**Issue by agenthala** [nordcloud/serverless-mocha-plugin#125] opened 2019-12-16 07:50 UTC
In v1.12.0 you made a fix in the test runner to enable also typescript tests. This feature would be nice to install it also over npm: https://www.npmjs.com/package/serverless-mocha-plugin

**Comment by garethmcc** [comment] 2020-01-14 14:12
Please can we release the support for 1.12 to npm as well

**Comment by KariHe** [comment] 2020-03-12 09:44
Duplicate of #127

**Closed** 2020-03-24 06:48 UTC
